package com.example.compose
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF855300)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffddb4)
val md_theme_light_onPrimaryContainer = Color(0xFF2a1700)
val md_theme_light_secondary = Color(0xFF705a41)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFfcdebd)
val md_theme_light_onSecondaryContainer = Color(0xFF271905)
val md_theme_light_tertiary = Color(0xFF54643e)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFd6e9b9)
val md_theme_light_onTertiaryContainer = Color(0xFF121f03)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF1f1b16)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF1f1b16)
val md_theme_light_surfaceVariant = Color(0xFFf1e0d0)
val md_theme_light_onSurfaceVariant = Color(0xFF504539)
val md_theme_light_outline = Color(0xFF827567)
val md_theme_light_inverseOnSurface = Color(0xFFf9efe7)
val md_theme_light_inverseSurface = Color(0xFF35302a)

val md_theme_dark_primary = Color(0xFFffb958)
val md_theme_dark_onPrimary = Color(0xFF472a00)
val md_theme_dark_primaryContainer = Color(0xFF653e00)
val md_theme_dark_onPrimaryContainer = Color(0xFFffddb4)
val md_theme_dark_secondary = Color(0xFFdec2a2)
val md_theme_dark_onSecondary = Color(0xFF3f2d16)
val md_theme_dark_secondaryContainer = Color(0xFF57432b)
val md_theme_dark_onSecondaryContainer = Color(0xFFfcdebd)
val md_theme_dark_tertiary = Color(0xFFbacd9e)
val md_theme_dark_onTertiary = Color(0xFF263513)
val md_theme_dark_tertiaryContainer = Color(0xFF3c4c28)
val md_theme_dark_onTertiaryContainer = Color(0xFFd6e9b9)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1f1b16)
val md_theme_dark_onBackground = Color(0xFFebe1d9)
val md_theme_dark_surface = Color(0xFF1f1b16)
val md_theme_dark_onSurface = Color(0xFFebe1d9)
val md_theme_dark_surfaceVariant = Color(0xFF504539)
val md_theme_dark_onSurfaceVariant = Color(0xFFd4c4b4)
val md_theme_dark_outline = Color(0xFF9c8e80)
val md_theme_dark_inverseOnSurface = Color(0xFF1f1b16)
val md_theme_dark_inverseSurface = Color(0xFFebe1d9)

val seed = Color(0xFFffa500)
val error = Color(0xFFba1b1b)